/******************************************************************************
 * Copyright 2017 The Apollo Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

/**
 * @file
 * @brief Defines the ControllerAgent class.
 */

#ifndef MODULES_CONTROL_CONTROLLER_CONTROLLER_AGENT_H_
#define MODULES_CONTROL_CONTROLLER_CONTROLLER_AGENT_H_

#include <cstdio>
#include <memory>
#include <vector>

#include "ros/include/ros/ros.h"

#include "modules/control/proto/control_cmd.pb.h"
#include "modules/control/proto/control_conf.pb.h"
#include "modules/planning/proto/planning.pb.h"

#include "modules/common/util/factory.h"
#include "modules/control/controller/controller.h"

/**
 * @namespace apollo::control
 * @brief apollo::control
 */
namespace apollo {
namespace control {

/**
 * @class ControllerAgent
 *
 * @brief manage all controllers declared in control config file.
 */

/**
 * @class ControllerAgent
 *
 * @brief 管理控制配置文件中声明的所有控制器。
 */
class ControllerAgent {
 public:
  /**
   * @brief initialize ControllerAgent
   * @param control_conf control configurations
   * @return Status initialization status
   */

    /**
   * @brief 初始化控制器代理
   * @param control_conf 控制配置
   * @return Status 初始化状态
   */
  common::Status Init(const ControlConf *control_conf);

  /**
   * @brief compute control command based on current vehicle status
   *        and target trajectory
   * @param localization vehicle location
   * @param chassis vehicle status e.g., speed, acceleration
   * @param trajectory trajectory generated by planning
   * @param cmd control command
   * @return Status computation status
   */

    /**
   * @brief 根据当前车辆状态和目标轨迹计算控制命令
   * @param localization 车辆位置
   * @param chassis 车辆状态，例如速度、加速度
   * @param trajectory 由规划生成的轨迹
   * @param cmd 控制命令
   * @return Status 计算状态
   */
  common::Status ComputeControlCommand(
      const localization::LocalizationEstimate *localization,
      const canbus::Chassis *chassis, const planning::ADCTrajectory *trajectory,
      control::ControlCommand *cmd);

  /**
   * @brief reset ControllerAgent
   * @return Status reset status
   */

    /**
   * @brief 重置控制器代理
   * @return Status 重置状态
   */
  common::Status Reset();

 private:
  /**
   * @brief
   * Register new controllers. If you need to add a new type of controller,
   * You should first register your controller in this function.
   */

    /**
   * @brief
   * 注册新的控制器。如果需要添加一种新的控制器类型，
   * 应该首先在此函数中注册你的控制器。
   */
  void RegisterControllers(const ControlConf *control_conf);

  common::Status InitializeConf(const ControlConf *control_conf);

  const ControlConf *control_conf_ = nullptr;
  common::util::Factory<ControlConf::ControllerType, Controller>
      controller_factory_;
  std::vector<std::unique_ptr<Controller>> controller_list_;
};

}  // namespace control
}  // namespace apollo

#endif  // MODULES_CONTROL_CONTROLLER_CONTROLLER_AGENT_H_
